//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.16 at 08:48:23 �ߌ� JST 
//


package vavi.util.openfeint.jaxb.readerboard;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vavi.util.openfeint.jaxb.leaderboard package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vavi.util.openfeint.jaxb.leaderboard
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore.User.ProfilePictureUrl }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore.User.ProfilePictureUrl createResourceSectionsResourceSectionResourcesHighScoreUserProfilePictureUrl() {
        return new ResourceSections.ResourceSection.Resources.HighScore.User.ProfilePictureUrl();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore createResourceSectionsResourceSectionResourcesHighScore() {
        return new ResourceSections.ResourceSection.Resources.HighScore();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore.User.LastPlayedGameId }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore.User.LastPlayedGameId createResourceSectionsResourceSectionResourcesHighScoreUserLastPlayedGameId() {
        return new ResourceSections.ResourceSection.Resources.HighScore.User.LastPlayedGameId();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore.DisplayText }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore.DisplayText createResourceSectionsResourceSectionResourcesHighScoreDisplayText() {
        return new ResourceSections.ResourceSection.Resources.HighScore.DisplayText();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore.UpdatedAt }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore.UpdatedAt createResourceSectionsResourceSectionResourcesHighScoreUpdatedAt() {
        return new ResourceSections.ResourceSection.Resources.HighScore.UpdatedAt();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore.User.Lng }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore.User.Lng createResourceSectionsResourceSectionResourcesHighScoreUserLng() {
        return new ResourceSections.ResourceSection.Resources.HighScore.User.Lng();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore.CustomData }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore.CustomData createResourceSectionsResourceSectionResourcesHighScoreCustomData() {
        return new ResourceSections.ResourceSection.Resources.HighScore.CustomData();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore.User.UploadedProfilePictureContentType }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore.User.UploadedProfilePictureContentType createResourceSectionsResourceSectionResourcesHighScoreUserUploadedProfilePictureContentType() {
        return new ResourceSections.ResourceSection.Resources.HighScore.User.UploadedProfilePictureContentType();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore.User }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore.User createResourceSectionsResourceSectionResourcesHighScoreUser() {
        return new ResourceSections.ResourceSection.Resources.HighScore.User();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore.Lat }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore.Lat createResourceSectionsResourceSectionResourcesHighScoreLat() {
        return new ResourceSections.ResourceSection.Resources.HighScore.Lat();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore.User.UploadedProfilePictureUpdatedAt }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore.User.UploadedProfilePictureUpdatedAt createResourceSectionsResourceSectionResourcesHighScoreUserUploadedProfilePictureUpdatedAt() {
        return new ResourceSections.ResourceSection.Resources.HighScore.User.UploadedProfilePictureUpdatedAt();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore.User.ProfilePictureSource }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore.User.ProfilePictureSource createResourceSectionsResourceSectionResourcesHighScoreUserProfilePictureSource() {
        return new ResourceSections.ResourceSection.Resources.HighScore.User.ProfilePictureSource();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore.User.UploadedProfilePictureFileSize }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore.User.UploadedProfilePictureFileSize createResourceSectionsResourceSectionResourcesHighScoreUserUploadedProfilePictureFileSize() {
        return new ResourceSections.ResourceSection.Resources.HighScore.User.UploadedProfilePictureFileSize();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore.User.ProfilePictureUpdatedAt }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore.User.ProfilePictureUpdatedAt createResourceSectionsResourceSectionResourcesHighScoreUserProfilePictureUpdatedAt() {
        return new ResourceSections.ResourceSection.Resources.HighScore.User.ProfilePictureUpdatedAt();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.PaginationHeader }
     * 
     */
    public ResourceSections.ResourceSection.Resources.PaginationHeader createResourceSectionsResourceSectionResourcesPaginationHeader() {
        return new ResourceSections.ResourceSection.Resources.PaginationHeader();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore.User.UploadedProfilePictureFileName }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore.User.UploadedProfilePictureFileName createResourceSectionsResourceSectionResourcesHighScoreUserUploadedProfilePictureFileName() {
        return new ResourceSections.ResourceSection.Resources.HighScore.User.UploadedProfilePictureFileName();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection }
     * 
     */
    public ResourceSections.ResourceSection createResourceSectionsResourceSection() {
        return new ResourceSections.ResourceSection();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore.Lng }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore.Lng createResourceSectionsResourceSectionResourcesHighScoreLng() {
        return new ResourceSections.ResourceSection.Resources.HighScore.Lng();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources.HighScore.User.Lat }
     * 
     */
    public ResourceSections.ResourceSection.Resources.HighScore.User.Lat createResourceSectionsResourceSectionResourcesHighScoreUserLat() {
        return new ResourceSections.ResourceSection.Resources.HighScore.User.Lat();
    }

    /**
     * Create an instance of {@link ResourceSections }
     * 
     */
    public ResourceSections createResourceSections() {
        return new ResourceSections();
    }

    /**
     * Create an instance of {@link ResourceSections.ResourceSection.Resources }
     * 
     */
    public ResourceSections.ResourceSection.Resources createResourceSectionsResourceSectionResources() {
        return new ResourceSections.ResourceSection.Resources();
    }

}
