// MP3IPodSyncDialog
// $Id: IPodSyncDialog.java,v 1.9 2003/06/06 16:11:34 axelwernicke Exp $
//
// Copyright (C) 2002-2003 Axel Wernicke <axel.wernicke@gmx.de>
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
package de.axelwernicke.mypod.gui;

import de.axelwernicke.mypod.SwingWorker;


/**
 *
 * @author  axel wernicke
 */
public class IPodSyncDialog extends javax.swing.JDialog {
    private SwingWorker worker = null;

    /** Creates new form IPodSyncDialog
     * @param parent
     * @param modal
     */
    public IPodSyncDialog(SwingWorker worker, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.worker = worker;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() //GEN-BEGIN:initComponents
     {
        java.awt.GridBagConstraints gridBagConstraints;

        statusLabel = new javax.swing.JLabel();
        statusContentLabel = new javax.swing.JLabel();
        totalProgressBar = new javax.swing.JProgressBar();
        fileNameLabel = new javax.swing.JLabel();
        fileNameContentLabel = new javax.swing.JLabel();
        copySpeedLabel = new javax.swing.JLabel();
        copySpeedContentLabel = new javax.swing.JLabel();
        fileSizeLabel = new javax.swing.JLabel();
        fileSizeContentLabel = new javax.swing.JLabel();
        copiedSizeLabel = new javax.swing.JLabel();
        copiedSizeContentLabel = new javax.swing.JLabel();
        totalSizeLabel = new javax.swing.JLabel();
        totalSizeContent = new javax.swing.JLabel();
        timeUsedLabel = new javax.swing.JLabel();
        timeUsedContentLabel = new javax.swing.JLabel();
        timeLeftLabel = new javax.swing.JLabel();
        timeLeftContentLabel = new javax.swing.JLabel();
        canelButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(GuiUtils.getStringLocalized("resource/language", "syncWithIPod"));
        setName("iPodSyncDialog");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    closeDialog(evt);
                }
            });

        statusLabel.setForeground(new java.awt.Color(102, 102, 153));
        statusLabel.setText(GuiUtils.getStringLocalized("resource/language", "status:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        getContentPane().add(statusLabel, gridBagConstraints);

        statusContentLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        statusContentLabel.setMaximumSize(new java.awt.Dimension(250, 14));
        statusContentLabel.setMinimumSize(new java.awt.Dimension(250, 14));
        statusContentLabel.setPreferredSize(new java.awt.Dimension(250, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 0, 0);
        getContentPane().add(statusContentLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(11, 17, 0, 17);
        getContentPane().add(totalProgressBar, gridBagConstraints);

        fileNameLabel.setForeground(new java.awt.Color(102, 102, 153));
        fileNameLabel.setText(GuiUtils.getStringLocalized("resource/language", "filename:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        getContentPane().add(fileNameLabel, gridBagConstraints);

        fileNameContentLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        fileNameContentLabel.setMaximumSize(new java.awt.Dimension(250, 14));
        fileNameContentLabel.setMinimumSize(new java.awt.Dimension(250, 14));
        fileNameContentLabel.setPreferredSize(new java.awt.Dimension(250, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 0, 12);
        getContentPane().add(fileNameContentLabel, gridBagConstraints);

        copySpeedLabel.setForeground(new java.awt.Color(102, 102, 153));
        copySpeedLabel.setText(GuiUtils.getStringLocalized("resource/language", "performance:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 17, 0, 0);
        getContentPane().add(copySpeedLabel, gridBagConstraints);

        copySpeedContentLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        copySpeedContentLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        copySpeedContentLabel.setMaximumSize(new java.awt.Dimension(75, 14));
        copySpeedContentLabel.setMinimumSize(new java.awt.Dimension(75, 14));
        copySpeedContentLabel.setPreferredSize(new java.awt.Dimension(75, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 0, 12);
        getContentPane().add(copySpeedContentLabel, gridBagConstraints);

        fileSizeLabel.setForeground(new java.awt.Color(102, 102, 153));
        fileSizeLabel.setText(GuiUtils.getStringLocalized("resource/language", "fileSize:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        getContentPane().add(fileSizeLabel, gridBagConstraints);

        fileSizeContentLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        fileSizeContentLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fileSizeContentLabel.setMaximumSize(new java.awt.Dimension(75, 14));
        fileSizeContentLabel.setMinimumSize(new java.awt.Dimension(75, 14));
        fileSizeContentLabel.setPreferredSize(new java.awt.Dimension(75, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 0, 0);
        getContentPane().add(fileSizeContentLabel, gridBagConstraints);

        copiedSizeLabel.setForeground(new java.awt.Color(102, 102, 153));
        copiedSizeLabel.setText(GuiUtils.getStringLocalized("resource/language", "copied:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 0, 0);
        getContentPane().add(copiedSizeLabel, gridBagConstraints);

        copiedSizeContentLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        copiedSizeContentLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        copiedSizeContentLabel.setMaximumSize(new java.awt.Dimension(75, 14));
        copiedSizeContentLabel.setMinimumSize(new java.awt.Dimension(75, 14));
        copiedSizeContentLabel.setPreferredSize(new java.awt.Dimension(75, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 11, 0, 0);
        getContentPane().add(copiedSizeContentLabel, gridBagConstraints);

        totalSizeLabel.setForeground(new java.awt.Color(102, 102, 153));
        totalSizeLabel.setText(GuiUtils.getStringLocalized("resource/language", "total:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 0, 0);
        getContentPane().add(totalSizeLabel, gridBagConstraints);

        totalSizeContent.setFont(new java.awt.Font("Dialog", 1, 10));
        totalSizeContent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalSizeContent.setMaximumSize(new java.awt.Dimension(75, 14));
        totalSizeContent.setMinimumSize(new java.awt.Dimension(75, 14));
        totalSizeContent.setPreferredSize(new java.awt.Dimension(75, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 11, 0, 0);
        getContentPane().add(totalSizeContent, gridBagConstraints);

        timeUsedLabel.setForeground(new java.awt.Color(102, 102, 153));
        timeUsedLabel.setText(GuiUtils.getStringLocalized("resource/language", "timeUsed:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 17, 0, 0);
        getContentPane().add(timeUsedLabel, gridBagConstraints);

        timeUsedContentLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        timeUsedContentLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeUsedContentLabel.setMaximumSize(new java.awt.Dimension(75, 14));
        timeUsedContentLabel.setMinimumSize(new java.awt.Dimension(75, 14));
        timeUsedContentLabel.setPreferredSize(new java.awt.Dimension(75, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 11, 0, 12);
        getContentPane().add(timeUsedContentLabel, gridBagConstraints);

        timeLeftLabel.setForeground(new java.awt.Color(102, 102, 153));
        timeLeftLabel.setText(GuiUtils.getStringLocalized("resource/language", "timeLeft:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 17, 0, 0);
        getContentPane().add(timeLeftLabel, gridBagConstraints);

        timeLeftContentLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        timeLeftContentLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeLeftContentLabel.setMaximumSize(new java.awt.Dimension(75, 14));
        timeLeftContentLabel.setMinimumSize(new java.awt.Dimension(75, 14));
        timeLeftContentLabel.setPreferredSize(new java.awt.Dimension(75, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 11, 0, 12);
        getContentPane().add(timeLeftContentLabel, gridBagConstraints);

        canelButton.setText(GuiUtils.getStringLocalized("resource/language", "cancel"));
        canelButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    canelButtonActionPerformed(evt);
                }
            });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 12, 0);
        getContentPane().add(canelButton, gridBagConstraints);

        pack();
    } //GEN-END:initComponents

    private void canelButtonActionPerformed(java.awt.event.ActionEvent evt) //GEN-FIRST:event_canelButtonActionPerformed
     { //GEN-HEADEREND:event_canelButtonActionPerformed
        if (worker != null) {
            worker.interrupt();
        }
    } //GEN-LAST:event_canelButtonActionPerformed

    /** Closes the dialog
     * @param evt
     */
    private void closeDialog(java.awt.event.WindowEvent evt) { //GEN-FIRST:event_closeDialog
        if (worker != null) {
            worker.interrupt();
        }
    } //GEN-LAST:event_closeDialog

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton canelButton;
    public javax.swing.JLabel copiedSizeContentLabel;
    private javax.swing.JLabel copiedSizeLabel;
    public javax.swing.JLabel copySpeedContentLabel;
    private javax.swing.JLabel copySpeedLabel;
    public javax.swing.JLabel fileNameContentLabel;
    private javax.swing.JLabel fileNameLabel;
    public javax.swing.JLabel fileSizeContentLabel;
    private javax.swing.JLabel fileSizeLabel;
    public javax.swing.JLabel statusContentLabel;
    private javax.swing.JLabel statusLabel;
    public javax.swing.JLabel timeLeftContentLabel;
    private javax.swing.JLabel timeLeftLabel;
    public javax.swing.JLabel timeUsedContentLabel;
    private javax.swing.JLabel timeUsedLabel;
    public javax.swing.JProgressBar totalProgressBar;
    public javax.swing.JLabel totalSizeContent;
    private javax.swing.JLabel totalSizeLabel;

    // End of variables declaration//GEN-END:variables
}
