// ReorganizeClipsProgressDialog
// $Id: ReorganizeClipsProgressDialog.java,v 1.7 2003/02/03 19:07:05 axelwernicke Exp $
//
// Copyright (C) 2002-2003 Axel Wernicke <axel.wernicke@gmx.de>
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
package de.axelwernicke.mypod.gui;

import de.axelwernicke.mypod.SwingWorker;


/**
 *
 * @author  axel wernicke
 */
public class ReorganizeClipsProgressDialog extends javax.swing.JDialog {
    private SwingWorker worker = null;

    /** Creates new form ReorganizeClipsProgressDialog */
    public ReorganizeClipsProgressDialog(SwingWorker worker, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.worker = worker;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() //GEN-BEGIN:initComponents
     {
        java.awt.GridBagConstraints gridBagConstraints;

        statusLabel = new javax.swing.JLabel();
        statusContentLabel = new javax.swing.JLabel();
        totalProgressBar = new javax.swing.JProgressBar();
        clipLabel = new javax.swing.JLabel();
        clipContentLabel = new javax.swing.JLabel();
        clipsRenamedLabel = new javax.swing.JLabel();
        clipsRenamedContentLabel = new javax.swing.JLabel();
        clipsMovedLabel = new javax.swing.JLabel();
        clipsMovedContentLabel = new javax.swing.JLabel();
        directoriesRemovedLabel = new javax.swing.JLabel();
        directoriesRemovedContentLabel = new javax.swing.JLabel();
        canelButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setName("reorganizeClipsDialog");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    closeDialog(evt);
                }
            });

        statusLabel.setForeground(new java.awt.Color(102, 102, 153));
        statusLabel.setText(GuiUtils.getStringLocalized("resource/language", "status:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        getContentPane().add(statusLabel, gridBagConstraints);

        statusContentLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        statusContentLabel.setMaximumSize(new java.awt.Dimension(250, 14));
        statusContentLabel.setMinimumSize(new java.awt.Dimension(200, 14));
        statusContentLabel.setPreferredSize(new java.awt.Dimension(200, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 0, 12);
        getContentPane().add(statusContentLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(11, 17, 0, 17);
        getContentPane().add(totalProgressBar, gridBagConstraints);

        clipLabel.setForeground(new java.awt.Color(102, 102, 153));
        clipLabel.setText(GuiUtils.getStringLocalized("resource/language", "clip:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        getContentPane().add(clipLabel, gridBagConstraints);

        clipContentLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        clipContentLabel.setMaximumSize(new java.awt.Dimension(250, 14));
        clipContentLabel.setMinimumSize(new java.awt.Dimension(250, 14));
        clipContentLabel.setPreferredSize(new java.awt.Dimension(250, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 0, 12);
        getContentPane().add(clipContentLabel, gridBagConstraints);

        clipsRenamedLabel.setForeground(new java.awt.Color(102, 102, 153));
        clipsRenamedLabel.setText(GuiUtils.getStringLocalized("resource/language", "clipsRenamed:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        getContentPane().add(clipsRenamedLabel, gridBagConstraints);

        clipsRenamedContentLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        clipsRenamedContentLabel.setMaximumSize(new java.awt.Dimension(75, 14));
        clipsRenamedContentLabel.setMinimumSize(new java.awt.Dimension(75, 14));
        clipsRenamedContentLabel.setPreferredSize(new java.awt.Dimension(75, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 0, 12);
        getContentPane().add(clipsRenamedContentLabel, gridBagConstraints);

        clipsMovedLabel.setForeground(new java.awt.Color(102, 102, 153));
        clipsMovedLabel.setText(GuiUtils.getStringLocalized("resource/language", "clipsMoved:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 0, 0);
        getContentPane().add(clipsMovedLabel, gridBagConstraints);

        clipsMovedContentLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        clipsMovedContentLabel.setMaximumSize(new java.awt.Dimension(75, 14));
        clipsMovedContentLabel.setMinimumSize(new java.awt.Dimension(75, 14));
        clipsMovedContentLabel.setPreferredSize(new java.awt.Dimension(75, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 0, 12);
        getContentPane().add(clipsMovedContentLabel, gridBagConstraints);

        directoriesRemovedLabel.setForeground(new java.awt.Color(102, 102, 153));
        directoriesRemovedLabel.setText(GuiUtils.getStringLocalized("resource/language", "directoriesRemoved:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        getContentPane().add(directoriesRemovedLabel, gridBagConstraints);

        directoriesRemovedContentLabel.setFont(new java.awt.Font("Dialog", 1, 10));
        directoriesRemovedContentLabel.setMaximumSize(new java.awt.Dimension(75, 14));
        directoriesRemovedContentLabel.setMinimumSize(new java.awt.Dimension(75, 14));
        directoriesRemovedContentLabel.setPreferredSize(new java.awt.Dimension(75, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 0, 12);
        getContentPane().add(directoriesRemovedContentLabel, gridBagConstraints);

        canelButton.setText(GuiUtils.getStringLocalized("resource/language", "cancel"));
        canelButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    canelButtonActionPerformed(evt);
                }
            });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(17, 12, 12, 12);
        getContentPane().add(canelButton, gridBagConstraints);

        pack();
    } //GEN-END:initComponents

    private void canelButtonActionPerformed(java.awt.event.ActionEvent evt) //GEN-FIRST:event_canelButtonActionPerformed
     { //GEN-HEADEREND:event_canelButtonActionPerformed
        if (worker != null) {
            worker.interrupt();
        }
    } //GEN-LAST:event_canelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) { //GEN-FIRST:event_closeDialog
        if (worker != null) {
            worker.interrupt();
        }
    } //GEN-LAST:event_closeDialog

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clipLabel;
    private javax.swing.JLabel clipsMovedLabel;
    private javax.swing.JLabel statusLabel;
    public javax.swing.JLabel clipContentLabel;
    public javax.swing.JLabel directoriesRemovedContentLabel;
    public javax.swing.JProgressBar totalProgressBar;
    public javax.swing.JLabel statusContentLabel;
    public javax.swing.JLabel clipsMovedContentLabel;
    private javax.swing.JButton canelButton;
    private javax.swing.JLabel clipsRenamedLabel;
    public javax.swing.JLabel clipsRenamedContentLabel;
    private javax.swing.JLabel directoriesRemovedLabel;

    // End of variables declaration//GEN-END:variables
}
